services:
  dealgoblin:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dealgoblin
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    init: true
    restart: unless-stopped
